version: "2"
services:
  app:
    build: .
    container_name: "app"
    ports:
     - "3000:3000"
    links:
     - mongo
    depends_on:
     - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
